[ninjabrainOverlay]
accentColor = [ 0, 255, 0 ]
allowedModes = []
alwaysShow = true
alwaysShowBoat = false
angleDisplay = 1
apiBaseUrl = 'http://127.0.0.1:52533'
bgColor = [ 55, 60, 66 ]
bgEnabled = true
bgOpacity = 1.0
boatStateMarginRight = 16.0
boatStateSize = 64.0
borderColor = [ 71, 74, 79 ]
borderRadius = 0.0
borderWidth = 0
buttonColor = [ 59, 66, 77 ]
certaintyColor = [ 0, 206, 41 ]
certaintyLowColor = [ 255, 0, 0 ]
certaintyMidColor = [ 255, 255, 0 ]
chromeColor = [ 46, 51, 61 ]
colSpacing = 36.0
columns = [
    { header = 'Location', id = 'coords', show = true, staticWidth = 0 },
    { header = '%', id = 'certainty', show = true, staticWidth = 0 },
    { header = 'Dist.', id = 'distance', show = true, staticWidth = 0 },
    { header = 'Nether', id = 'nether', show = true, staticWidth = 0 },
    { header = 'Angle', id = 'angle', show = true, staticWidth = 0 }
]
contentPaddingBottom = 0.0
contentPaddingTop = 0.0
coordNegativeColor = [ 255, 255, 255 ]
coordPositiveColor = [ 255, 255, 255 ]
coordsDisplay = 'block'
cornerRadius = 0.0
customFontPath = 'fonts/OpenSans-Regular.ttf'
dataColor = [ 255, 255, 255 ]
dividerColor = [ 42, 46, 50 ]
divineTextColor = [ 229, 229, 229 ]
enabled = true
eyeThrowRows = 3
failureAnchor = 'topLeft'
failureDrawOrder = 0
failureLineGap = 64.0
failureMarginBottom = 32.0
failureMarginLeft = 24.0
failureMarginRight = 48.0
failureMarginTop = 20.0
failureOffsetX = 0.0
failureOffsetY = 0.0
blindAnchor = 'topLeft'
blindDrawOrder = 0
blindLineGap = 64.0
blindMarginBottom = 32.0
blindMarginLeft = 24.0
blindMarginRight = 48.0
blindMarginTop = 20.0
blindOffsetX = 0.0
blindOffsetY = 0.0
fontAntialiasing = false
headerDividerColor = [ 33, 37, 41 ]
headerFillColor = [ 45, 50, 56 ]
informationMessagesAnchor = 'topLeft'
informationMessagesDrawOrder = 1
informationMessagesFontScale = 0.75
informationMessagesIconScale = 1.3
informationMessagesIconTextMargin = 24.0
informationMessagesMarginBottom = 18.0
informationMessagesMarginLeft = 14.0
informationMessagesMarginRight = 0.0
informationMessagesMarginTop = 12.0
informationMessagesMinWidth = 285.0
informationMessagesOffsetX = 0.0
informationMessagesOffsetY = 0.0
informationMessagesPlacement = 'middle'
layoutStyle = 'compact'
onlyOnMyScreen = false
onlyOnObs = false
outlineColor = [ 0, 0, 0, 220 ]
outlineWidth = 0
overlayOpacity = 1.0
overlayScale = 0.3
relativeTo = 'topLeftScreen'
resultsAnchor = 'topLeft'
resultsColumnGap = 0.0
resultsDrawOrder = 0
resultsHeaderPaddingY = 2.0
resultsMarginBottom = 0.0
resultsMarginLeft = 0.0
resultsMarginRight = 0.0
resultsMarginTop = 0.0
resultsOffsetX = 0.0
resultsOffsetY = 0.0
rowSpacing = 2.0
sectionLayoutMode = 'flow'
showAllPreds = false
showBoatStateInTopBar = true
showDirectionToStronghold = true
showEyeOverlay = true
showRowStripes = true
showSeparators = true
showThrowDetails = true
showTitleBar = false
showWindowControls = false
shownPredictions = 5
sidePadding = 10.0
staticColumnWidths = true
subpixelNegativeColor = [ 204, 110, 114 ]
subpixelPositiveColor = [ 117, 204, 108 ]
textColor = [ 229, 229, 229 ]
throwsAnchor = 'topLeft'
throwsBackgroundColor = [ 51, 56, 61 ]
throwsDrawOrder = 2
throwsHeaderPaddingY = 3.0
throwsMarginBottom = 0.0
throwsMarginLeft = 0.0
throwsMarginRight = 0.0
throwsMarginTop = 0.0
throwsOffsetX = 0.0
throwsOffsetY = 0.0
throwsRowPaddingY = 0.0
throwsTextColor = [ 192, 192, 192 ]
titleText = 'Ninjabrain Bot'
titleTextColor = [ 255, 255, 255 ]
versionTextColor = [ 194, 194, 194 ]
x = 0
y = 0